kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: cmake
  image: nextcloudci/client-5.12:client-5.12-12
  commands:
  - cmake .
  - make