kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: Start build
  image: alpine
  commands:
  - echo start build

- name: cmake
  image: nextcloudci/client-5.12:client-5.12-12
  commands:
  - mkdir build
  - cd build
  - cmake ..
  - make

- name: Install dependencies
  image: alpine
  commands:
  - echo Install dependencies

- name: testDep
  image: gcc
  commands:
  - pwd
  - apt-get -qq update -y && apt-get -qq update
  - apt-get -qq install -y cmake libgtest-dev > /dev/null
  - export PROJ_PATH=/drone/src
  - cd /usr/src/gtest && cmake CMakeLists.txt && make && cd lib && cp *.a /usr/lib && cd -